# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f297d4b6ad88a0d3eed56db9bf6f4f4992b726a367560b3a9a017a27f830565f88339f701c8be31566224072785cfec989f7cb51d12ae2fd99b83dc4426bf70c

test:
  secret_key_base: 5b0643d4acbcca8a9f60d2a38383a55a73ebba777e75aac17dc5aafbfa82f1491d49819884000b1e92806d4d6288f8c4515a0c70be6b37625fd77d775a3c6b75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
